### ISSUE TITLE
feature request: Docker Provider

### ISSUE THREAD

**Issue by oops-lgtm** [laixintao/lobbyboy#22]
in Chinese:

验证场景：
工作需要，经常使用不同的数据库，看看不同的数据库的行为不同，比方说mysql的5.7版本，8.0版本，mariadb甚至oracle。因此我写了一个[脚本](https://github.com/oops-lgtm/dotfiles/blob/main/bin/dockersql)来干这个事情。

看了你的文章[介绍 Lobbyboy 项目](https://www.kawabangga.com/posts/4576)，在想`lobbyboy`可能能搞。

期待。

**Comment by laixintao** [comment]
hi 感谢，这个 provider 我也计划做的。考虑用 https://github.com/ContainerSSH/ContainerSSH 或者 waveworks 的 https://github.com/weaveworks/footloose 来实现。我参考下你的脚本
